apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-oarr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-oarr
    app.kubernetes.io/part-of: devfile-sample-go-basic-3
  name: devfile-sample-go-basic-oarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-oarr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-oarr
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jdanek-tenant/devfile-sample-go-basic-3/devfile-sample-go-basic-oarr@sha256:3695f3b3cb78adc8c92e96e772958e36bc0e15f24508d3931b5a1e26bb92628c
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
